---

- name: Install OpenVPN
  apt:
    name:
      - openvpn
    state: present
    update_cache: yes

- name: Create default config from template
  template:
    src: default.conf.j2
    dest: /etc/openvpn/default.conf
  notify: Start OpenVPN service  

